'use client';

import { FormEvent, useState } from 'react';

const cases = [
  { tag: 'Брендинговое агентство', turnover: '53 млн ₽ / квартал', task: 'Внедрили учёт проектов в 1С, калькулятор рентабельности и оптимизировали маркетинг.', metrics: [['66 млн ₽', 'выручка'], ['55%', 'рентабельность ВП'], ['-10%', 'косвенные расходы']] },
  { tag: 'Сеть стоматологий', turnover: '15 млн ₽ / месяц', task: 'Автоматизировали учёт в Финтабло, пересмотрели цены, маркетинг и мотивацию врачей.', metrics: [['×2', 'рост выручки'], ['60%', 'маржинальность'], ['15%', 'рентабельность ЧП']] },
];
const services = [['Прозрачный учёт', 'Выстрою управленческий учёт, которому можно доверять.'], ['Планирование', 'Настрою план денег, доходов и расходов.'], ['Точки утечек', 'Найду потери прибыли и зоны для роста.'], ['Дивиденды', 'Выстрою регулярную систему фондов и выплат.'], ['Решения на цифрах', 'Помогу собственнику видеть картину и действовать вовремя.']];

export default function Home() {
  const [sent, setSent] = useState(false);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSent(true); }
  return <main>
    <section className="hero" id="top"><nav className="nav wrap"><a className="brand" href="#top"><i>✦</i> Елена Марцинишина</a><div className="navlinks"><a href="#about">Обо мне</a><a href="#cases">Кейсы</a><a href="#process">Как работаю</a></div><a className="nav-cta" href="#contact">Обсудить задачу</a></nav><div className="hero-glow" /><div className="hero-content wrap"><p className="eyebrow light">Финансовый директор для бизнеса</p><h1>Превращаю цифры<br />в уверенные решения</h1><p className="hero-copy">Выстрою управленческий учёт, найду точки роста прибыли и дам собственнику понятную картину бизнеса.</p><a className="button primary" href="#contact">Записаться на диагностику <span>↗</span></a></div><div className="hero-stats wrap"><div><strong>17 лет</strong><span>в финансах</span></div><div><strong>10 лет</strong><span>главным бухгалтером</span></div><div><strong>3 года</strong><span>финансовым директором для бизнеса</span></div></div></section>
    <section className="intro wrap" id="about"><div><p className="eyebrow">Обо мне</p><h2>Финансы - это<br />система для роста</h2></div><div className="intro-right"><p className="lead">Я Елена Марцинишина, финансовый директор с 17-летним опытом. Помогаю предпринимателям перестать управлять «на ощущениях» и опираться на точные цифры.</p><p>Работаю проактивно: не просто собираю отчёты, а нахожу, что именно влияет на прибыль, и вместе с командой внедряю изменения без лишней бюрократии.</p><a className="text-link" href="#contact">Познакомиться на встрече <span>→</span></a></div><img className="portrait" src="/elena-portrait.jpg" alt="Елена Марцинишина" /></section>
    <section className="services"><div className="wrap"><p className="eyebrow">Чем могу быть полезна</p><h2>Финансовая опора<br />вашего бизнеса</h2><div className="services-grid">{services.map(([title, text], i) => <article className="service-card" key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p><b>↗</b></article>)}</div></div></section>
    <section className="cases wrap" id="cases"><div className="section-head"><div><p className="eyebrow">Результаты</p><h2>Кейсы, где цифры<br />изменили бизнес</h2></div><p>Без абстрактных рекомендаций.<br />Только измеримые действия и результат.</p></div><div className="case-grid">{cases.map((item, i) => <article className="case-card" key={item.tag}><p className="case-num">Кейс 0{i + 1}</p><h3>{item.tag}</h3><p className="turnover">Оборот: {item.turnover}</p><p className="case-task">{item.task}</p><div className="metrics">{item.metrics.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></article>)}</div></section>
    <section className="industries"><div className="wrap"><p className="eyebrow light">С кем работаю</p><h2>Бизнесы, которым<br />важен результат</h2><div className="industry-list"><span>Стоматологии</span><span>Торговля</span><span>Строительство</span><span>Агентства</span><span>Услуги</span></div></div></section>
    <section className="process wrap" id="process"><p className="eyebrow">Как работаем</p><h2>От запроса<br />к управляемому бизнесу</h2><div className="steps"><article><span>01</span><h3>Диагностика</h3><p>1-3 встречи: цели, запросы и аудит текущей системы учёта.</p></article><article><span>02</span><h3>Дорожная карта</h3><p>Расставляем приоритеты, оцениваем риски и ресурсы команды.</p></article><article><span>03</span><h3>Реализация</h3><p>Внедряем поэтапно, сохраняя рабочие процессы бизнеса.</p></article><article><span>04</span><h3>Контроль роста</h3><p>Настраиваем отчёты, финмодель и KPI для устойчивых решений.</p></article></div></section>
    <section className="contact" id="contact"><div className="wrap contact-layout"><div><p className="eyebrow light">Первый шаг</p><h2>Давайте разберём<br />вашу ситуацию</h2><p>На диагностике обсудим, где бизнес теряет деньги и с чего начать изменения.</p><div className="direct"><a href="tel:+79067219115">+7 906 721-91-15</a><a href="https://t.me/ElenaMartsinishina" target="_blank">Telegram @ElenaMartsinishina</a></div></div><form onSubmit={submit}>{sent ? <div className="success"><b>Спасибо!</b><p>Заявка принята. Я свяжусь с вами в ближайшее время.</p></div> : <><label>Ваше имя<input required placeholder="Как к вам обращаться" /></label><label>Телефон или Telegram<input required placeholder="Для связи" /></label><label>Коротко о задаче<textarea placeholder="Что сейчас важно решить?" rows={3}/></label><button className="button primary" type="submit">Отправить заявку <span>↗</span></button><small>Нажимая кнопку, вы соглашаетесь на обработку персональных данных.</small></>}</form></div></section>
    <footer className="footer wrap"><a className="brand" href="#top"><i>✦</i> Елена Марцинишина</a><span>Финансовый директор для бизнеса</span><span>© 2026</span></footer>
  </main>;
}
